name: Tailscale ACLs
on:
  push:
    branches:
      - main
jobs:
  acls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Tailscale ACLs
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: test
      - name: Apply Tailscale ACLs
        if: github.ref == 'refs/heads/main'
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply
